using System;

namespace Parser
{
    class Products
    {
        public String[] productsNamesArray = new string[] {
                "Абсент Xenta (Ксента) 0,5л",
                "Абсент Xenta (Ксента) 0,7л",
                "Абсент Xenta (Ксента) 1,0л",
                "Аперитив Aperol (Апероль) 0,7л",
                "Аперитив Aperol (Апероль) 1,0л",
                "Аперитив Campari Bitter 0,5л",
                "Аперитив Campari Bitter 1,0л",
                "Виски Ballantine's (Баллантайнс) Finest 0,5л",
                "Виски Ballantine's (Баллантайнс) Finest 0,7л",
                "Виски Ballantine's (Баллантайнс) Finest 1,0л",
                "Виски Bushmills (Бушмиллс) Original 0,5л",
                "Виски Bushmills (Бушмиллс) Original 0,7л",
                "Виски Bushmills (Бушмиллс) Original 1,0л",
                "Виски Bushmills (Бушмилс) Black Bush 0,7л",
                "Виски Bushmills (Бушмилс) Black Bush 1,0л",
                "Виски Bushmills (Бушмилс) Irish Honey 0,7л",
                "Виски Bushmills (Бушмиллс) Single Malt 10 yo 0,7л",
                "Виски Bushmills (Бушмиллс) Single Malt 16 yo 0,7л",
                "Виски Bushmills (Бушмиллс) Single Malt 21 yo 0,7л",
                "Виски Chivas Regal (Чивас Ригал) 12 лет 0,375л в коробке",
                "Виски Chivas Regal (Чивас Ригал) 12 лет 0,5л в коробке",
                "Виски Chivas Regal (Чивас Ригал) 12 лет 0,7л в коробке",
                "Виски Chivas Regal (Чивас Ригал) 12 лет 1,0л в коробке",
                "Виски Chivas Regal (Чивас Ригал) 12 лет 0,75л в металлической коробке",
                "Виски Chivas Regal (Чивас Ригал) 12 лет 0,7л в коробке с двумя стаканами",
                "Виски Chivas Regal (Чивас Ригал) 12 лет 4,5л",
                "Виски Chivas Regal (Чивас Ригал) 18 лет 0,7л в коробке",
                "Виски Chivas Regal (Чивас Ригал) 18 лет 1,0л в коробке",
                "Виски Chivas Regal (Чивас Ригал) 25 лет 0,7л в коробке",
                "Виски Chivas Regal Extra 0,7л в коробке",
                "Виски Grant's Family Reserve 0,5л",
                "Виски Grant's Family Reserve 0,7л",
                "Виски Grant's Family Reserve 1,0л",
                "Виски Grant's Family Reserve 4,5 л. в кор.",
                "Виски Grant's Sherry Cask 0,7л",
                "Виски Grant's 8 лет 0,7л",
                "Виски Grant's 12 лет 0,75 л. в кор.",
                "Виски Grant's 18 лет 0,75л",
                "Виски Hankey Bannister (Ханки Баннистер) 0,5л",
                "Виски Hankey Bannister (Ханки Баннистер) 0,7л",
                "Виски Hankey Bannister (Ханки Баннистер) 1,0л",
                "Виски Jack Daniel's (Джек Дэниэлс) 0,375л",
                "Виски Jack Daniel's (Джек Дэниэлс) 0,5л",
                "Виски Jack Daniel's (Джек Дэниэлс) 0,7л",
                "Виски Jack Daniel's (Джек Дэниэлс) 1,0л",
                "Виски Jack Daniel's (Джек Дэниэлс) 3,0л",
                "Виски Jack Daniel's (Джек Дэниэлс) 0,7л в металлической коробке",
                "Виски Jack Daniel's (Джек Дэниэлс) 1,0л в металлической коробке",
                "Виски Jack Daniel's (Джек Дэниэлс) 0,7л c 2-мя бокалами в металлической коробке",
                "Виски Jack Daniel's (Джек Дэниэлс) Master Distiller №4 0,7л",
                "Виски Jack Daniel's (Джек Дэниэлс Медовый) Tennessee Honey 0,5л",
                "Виски Jack Daniel's (Джек Дэниэлс Медовый) Tennessee Honey 0,7л",
                "Виски Gentleman Jack (Джентельмен Джек) 0,7л",
                "Виски Jack Daniel's Single Barrel 0,7л",
                "Виски Jameson (Джемисон) 0,5л",
                "Виски Jameson (Джемисон) 0,7л",
                "Виски Jameson (Джемисон) 0,7л в металлической коробке",
                "Виски Jameson (Джемисон) 0,7л с 2-мя бокалами",
                "Виски Jameson (Джемисон) 1,0л",
                "Виски Jameson (Джемисон) 4,5л",
                "Виски Jameson (Джемисон) Select Reserve 0,7л",
                "Виски Jameson (Джемисон) Black Barrel 0,7л в коробке",
                "Виски Jim Beam (Джим Бим) 0,5л",
                "Виски Jim Beam (Джим Бим) 0,7л",
                "Виски Jim Beam (Джим Бим) 1,0л",
                "Виски Jim Beam Red Stag (Джим Бим Ред Стаг) 0,7л",
                "Виски Jim Beam Red Stag (Джим Бим Ред Стаг) 1,0л",
                "Виски Jim Beam Honey (Джим Бим Медовый) 0,7л",
                "Виски Jim Beam Apple (Джим Бим Яблоко) 0,7л",
                "Виски Jim Beam Devil’s Cut (Джим Бим Девилс Кат) 0,7л",
                "Виски Red Label (Джонни Уокер Ред Лейбл) 0,5л",
                "Виски Red Label (Джонни Уокер Ред Лейбл) 0,7л",
                "Виски Red Label (Джонни Уокер Ред Лейбл) 1,0л",
                "Виски Black Label (Джонни Уокер Блек Лейбл) 0,5л",
                "Виски Black Label (Джонни Уокер Блек Лейбл) 0,7л",
                "Виски Black Label (Джонни Уокер Блек Лейбл) 0,7л с 2-мя стаканами в коробке",
                "Виски Black Label (Джонни Уокер Блек Лейбл) 1,0л",
                "Виски Gold Label (Джонни Уокер Голд Лейбл) 0,7л",
                "Виски Blue Label (Джонни Уокер Блю Лейбл) 0,75л в коробке",
                "Виски Platinum Label (Джонни Уокер Платинум Лейбл) 18YO 0,7л в коробке",
                "Виски Tullamore Dew Original 0,5л",
                "Виски Tullamore Dew Original 0,7л",
                "Виски Tullamore Dew Original 1,0л",
                "Виски Tullamore Dew Original 0,7л + 2 стакана в коробке",
                "Виски Tullamore Dew Phoenix 0,7л",
                "Виски Tullamore Dew 10 yo Malt 0,7л",
                "Виски Tullamore Dew 12 yo 0,7л",
                "Виски White Horse (Уайт Хорс) 0,35л",
                "Виски White Horse (Уайт Хорс) 0,5л",
                "Виски White Horse (Уайт Хорс) 0,7л в коробке",
                "Виски White Horse (Уайт Хорс) 1,0л в коробке",
                "Виски White Horse (Уайт Хорс) 1900 0,5л",
                "Виски White Horse (Уайт Хорс) 1900 0,7л",
                "Виски (бурбон) Wild Turkey 81 0,7л",
                "Виски (бурбон) Wild Turkey 81 1,0л",
                "Виски (бурбон) Wild Turkey 101 0,7л",
                "Виски (бурбон) Wild Turkey 101 1,0л",
                "Виски (бурбон) Wild Turkey Rye 0,7л",
                "Виски (бурбон) Wild Turkey American Honey 0,7л",
                "Джин Beefeater (Бифитер) 0,5л",
                "Джин Beefeater (Бифитер) 0,7л",
                "Джин Beefeater (Бифитер) 1,0л",
                "Джин Beefeater (Бифитер) 1,75л",
                "Джин Bombay Sapphire (Бомбей Сапфир) 47% 0,5л",
                "Джин Bombay Sapphire (Бомбей Сапфир) 47% 0,75л",
                "Джин Bombay Sapphire (Бомбей Сапфир) 47% 1,0л",
                "Джин Finsbury (Финсбери) 0,7л",
                "Джин Finsbury (Финсбери) 1,0л",
                "Джин Finsbury Platinum (Финсбери Платинум) 0,7л",
                "Джин Finsbury Platinum (Финсбери Платинум) 1,0л",
                "Джин Gordon's 0,75л",
                "Джин Gordon's 1,0л",
                "Джин Gordon's 2,0л",
                "Джин Seagram's Extra Dry 0,75л",
                "Джин Seagram's Extra Dry 1,0л",
                "Джин Seagram's Twisted Gin Lime 0,75л",
                "Джин Seagram's Twisted Gin Lime 1,0л",
                "Вино игристое Fiorelli Fragolino Bianco (Фиорелли Фраголино Бьянко) 0,75л",
                "Вино игристое Fiorelli Fragolino Pesca (Фиорелли Фраголино Песка) 0,75л",
                "Вино игристое Fiorelli Fragolino Rosso (Фиорелли Фраголино Россо) 0,75л",
                "Вино игристое Martini Asti (Мартини Асти) 0,75л 7.5%",
                "Вино игристое Мартини Просекко 0,75л 11,5%",
                "Вино игристое Cinzano Asti 0,75л в коробке",
                "Вино игристое Asti Mondoro 0,75л в коробке",
                "Ликер Baileys (Бэйлис) Original 0,375л",
                "Ликер Baileys (Бэйлис) Original 0,5л",
                "Ликер Baileys (Бэйлис) Original 0,7л",
                "Ликер Baileys (Бэйлис) Original 1,0л",
                "Ликер Cointreau (Куантро) 0,35л",
                "Ликер Cointreau (Куантро) 0,5л",
                "Ликер Cointreau (Куантро) 0,7л",
                "Ликер Cointreau (Куантро) 1,0л",
                "Ликер Jagermeister (Егермейстер) 0,375л",
                "Ликер Jagermeister (Егермейстер) 0,5л",
                "Ликер Jagermeister (Егермейстер) 0,7л",
                "Ликер Jagermeister (Егермейстер) 1,0л",
                "Ликер Malibu (Малибу) 0,5л",
                "Ликер Malibu (Малибу) 0,7л",
                "Ликер Malibu (Малибу) 1,0л",
                "Ликер Sheridan's (Шериданс) 0,5л",
                "Ликер Sheridan's (Шериданс) 0,7л",
                "Ликер De Kuyper (Де Кайпер) Advocaat 0,7л",
                "Ликер De Kuyper Apricot Brandy 0,7л",
                "Ликер De Kuyper (Де Кайпер) Blue Curacao 0,7л",
                "Ликер De Kuyper Butterscotch Caramel 0,7л",
                "Ликер De Kuyper Cherry 0,7л",
                "Ликер De Kuyper Coconut 0,7л",
                "Ликер De Kuyper Creme de Bananes 0,7л",
                "Ликер De Kuyper Creme de Cafe 0,7л",
                "Ликер De Kuyper Creme de Cassis 0,7л",
                "Ликер De Kuyper Melon 0,7л",
                "Ликер De Kuyper (Де Кайпер) Pisang 0,7л",
                "Ликер De Kuyper (Де Кайпер) Triple Sec 0,7л",
                "Ликер De Kuyper Wild Strawberry 0,7л",
                "Ликер Воларе Elderflower 0,7л",
                "Ликер Volare Sprizzer 0,7л",
                "Ликер Volare Blue Curacao (Воларе Блю Курасао) 0,7л",
                "Ликер Volare Grenadin, Гренадин 0,7л",
                "Ликер Volare Espresso Coffee, Воларе Кофе Эспрессо 0,7л",
                "Ликер Volare Kiwi, Воларе Киви 0,7л",
                "Ликер Volare Triple Sec, Воларе Трипл Сек 0,7л",
                "Ликер Volare Coconut, Воларе Кокос 0,7л",
                "Ром Бакарди Карта Бланка (Bacardi Carta Blanca) 0,5л",
                "Ром Бакарди Карта Бланка (Bacardi Carta Blanca) 0,7л",
                "Ром Бакарди Карта Бланка (Bacardi Carta Blanca) 1,0л",
                "Ром Бакарди Карта Негра 0,5л",
                "Ром Бакарди Карта Негра 0,7л",
                "Ром Бакарди Карта Негра 1,0л",
                "Ром Бакарди Карта Оро 0,5л",
                "Ром Бакарди Карта Оро 0,7л",
                "Ром Бакарди Карта Оро 1,0л",
                "Ром Бакарди Оукхарт Ориджинал 0,5л",
                "Ром Бакарди Оукхарт Ориджинал 0,7л",
                "Ром Бакарди Оукхарт Ориджинал 1,0л",
                "Ром Captain Morgan Spiced Gold (Капитан Морган Спайсед Голд) 0,5л",
                "Ром Captain Morgan Spiced Gold (Капитан Морган Спайсед Голд) 0,7л",
                "Ром Captain Morgan Spiced Gold (Капитан Морган Спайсед Голд) 0,7л + кружка",
                "Ром Captain Morgan Spiced Gold (Капитан Морган Спайсед Голд) 1,0л",
                "Ром Captain Morgan Jamaica (Капитан Морган Ямайка) 0,5л",
                "Ром Captain Morgan Jamaica (Капитан Морган Ямайка) 0,7л",
                "Ром Captain Morgan Jamaica (Капитан Морган Ямайка) 1,0л",
                "Ром Captain Morgan White (Капитан Морган Уайт) 1л",
                "Ром Captain Morgan Black Spiced (Капитан Морган Блэк Спайсед) 0,7л",
                "Ром Havana Club Anejo (Гавана Клаб Аньехо) 3 years 0,5л",
                "Ром Havana Club Anejo (Гавана Клаб Аньехо) 3 years 0,7л",
                "Ром Havana Club Anejo (Гавана Клаб Аньехо) 3 years 1,0л",
                "Ром Havana Club (Гавана Клаб) Anejo 7 Anos 0,75л",
                "Ром Havana Club (Гавана Клаб) Anejo 7 Anos 1,0л",
                "Ром Havana Club Anejo Especial (Гавана Клаб) 0,7л",
                "Ром Havana Club Anejo Especial (Гавана Клаб) 1,0л",
                "Рон Барсело Аньехо (Ron Barcelo Anejo) 37,5% 0,7л",
                "Рон Барсело Гран Аньехо (Barcelo Gran Anejo) 37,5% 0,7л",
                "Рон Барсело Гран Платинум (Barcelo Gran Platinum) 37,5% 0,7л",
                "Рон Барсело Империал (Barcelo Imperial) 38% 0,7л",
                "Текила El Jimador Blanco (Эль Химадор Бланко) 0,7л 38% алк.",
                "Текила El Jimador Blanco (Эль Химадор Бланко) 1,0л 38% алк.",
                "Текила El Jimador Reposado (Эль Химадор Репосадо) 0,7л",
                "Текила El Jimador Reposado (Эль Химадор Репосадо) 1,0л",
                "Текила Espolon Blanco (Эсполон Бланко) 0,75л",
                "Текила Espolon Reposado (Эсполон Репосадо) 0,75л",
                "Текила Sauza Gold (Сауза Голд) 0,7л",
                "Текила Sauza Gold (Сауза Голд) 1,0л",
                "Текила Sauza Silver (Сауза Сильвер) 0,7л",
                "Текила Sauza Silver (Сауза Сильвер) 1,0л",
                "Текила Jose Cuervo (Хосе Куэрво) Especial Reposado 0,5 л",
                "Текила Jose Cuervo (Хосе Куэрво) Especial Reposado 0,7л",
                "Текила Jose Cuervo (Хосе Куэрво) Especial Reposado 1л",
                "Текила Jose Cuervo Especial Silver (Хосе Куэрво Сильвер) 0,5 л",
                "Текила Jose Cuervo Especial Silver (Хосе Куэрво Сильвер) 0,7 л",
                "Текила Jose Cuervo Especial Silver (Хосе Куэрво Сильвер) 1л",
                "Текила Olmeca Blanco (Ольмека Бланко) 0,5л.",
                "Текила Olmeca Blanco (Ольмека Бланко) 0,7л.",
                "Текила Olmeca Blanco (Ольмека Бланко) 1л.",
                "Текила Olmeca Gold (Ольмека Голд) 0,5 л. 38%",
                "Текила Olmeca Gold (Ольмека Голд) 0,7 л.",
                "Текила Olmeca Gold (Ольмека Голд) 1л.",
                "Ром Pott 0.7л 40% алк.",
                "Ром Pott 0.7л 54% алк.",
                "Ром Captain Gold 0,7л",
                "Ром Captain Silver 0,7л",
                "Ликер Marie Brizard Amaretto 0,7 л",
                "Ликер Becherovka Бехеровка 0,5л",
                "Ликер Becherovka Бехеровка 0,7л",
                "Ликер Becherovka Бехеровка 1л",
                "Водка SKYY 0,5л",
                "Водка SKYY 0,7л",
                "Водка SKYY 1,0л",
                "Водка SKYY INFUSIONS Citrus (лимон) 0,7л",
                "Водка SKYY INFUSIONS Passion Fruit (маракуя) 0,7л",
                "Водка Финляндия 0,5л",
                "Водка Финляндия 0,7л",
                "Водка Финляндия 1,0л",
                "Водка Финляндия 1,75л",
                "Водка Финляндия Грейпфрут 0,5л",
                "Водка Финляндия Грейпфрут 1,0л",
                "Водка Финляндия Клюква белая 0,5л",
                "Водка Финляндия Клюква белая 0,7л",
                "Водка Финляндия Клюква белая 1,0л",
                "Водка Финляндия Клюква красная 0,5л",
                "Водка Финляндия Клюква красная 1,0л",
                "Водка Финляндия Лайм 0,5л",
                "Водка Финляндия Лайм 1,0л",
                "Водка Финляндия Черная смородина 0,5л",
                "Водка Финляндия Черная смородина 1,0л",
                "Водка особая Nemiroff Горилка 0.5л",
                "Водка особая Nemiroff Горилка 0.7л",
                "Водка особая Nemiroff Горилка 1,0л",
                "Водка Перша Гільдія Знатна 0,5л",
                "Водка Перша Гільдія Знатна 0,7л",
                "Водка Absolut 0,5л",
                "Водка Absolut 0,7л",
                "Водка Absolut 1,0л",
                "Виски Bell’s Original 0,5л",
                "Виски Bell’s Original 0,7л",
                "Виски Bell’s Original 1,0л",
                "Виски Black & White 0,7л",
                "Виски Black & White 1,0л",
                "Бурбон Bulleit Bourbon Буллет 0,7л",
                "Виски Фэймос Граус 0,5л",
                "Виски Фэймос Граус 0,7л",
                "Виски Фэймос Граус 1,0л",
                "Бренди Гидели 0,5л",
                "Бренди Асканели 0,5л",
                "Бренди Saint Remy VSOP 0,5л",
                "Бренди Saint Remy VSOP 0,7л",
                "Бренди Saint Remy XO 0,7л",
                "Бренди Метакса Metaxa 12* 0,7л",
                "Бренди Метакса Metaxa 5* 0,5л",
                "Бренди Метакса Metaxa 5* 0,7л",
                "Бренди Метакса Metaxa 5* 1,0л",
                "Бренди Метакса Metaxa 7* 0,5л",
                "Бренди Метакса Metaxa 7* 0,7л",
                "Бренди Метакса Metaxa Private Reserve 0,7л в коробке",
                "Бренди Torres 10 лет 0,7л",
                "Бренди Torres 10 лет 0,7л в коробке",
                "Биттер Angostura Aromatic 0,2л",
                "Бальзам Herbal Park 35% 0,5 л",
                "Бальзам Riga Black Balsam 0,5 л",
                "Бальзам Riga Black Balsam 0,7 л",
                "Бальзам Riga Black Balsam Currant черная смородина 0,5 л",
                "Бальзам Riga Black Balsam Currant черная смородина 0,7л"

            };
    }
}
